name: reroot_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - snakemake
  - numpy
  - pandas
  - pip
  - pip:
      - taxoniumtools
      - phylo-treetime
      - treeswift
